# Generated by Django 3.2.5 on 2021-09-07 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emoji_name',
            old_name='name',
            new_name='ename',
        ),
    ]
